PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

DROP TABLE IF EXISTS categories;
CREATE TABLE categories (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE, name VARCHAR (32));

DROP TABLE IF EXISTS courses;
CREATE TABLE courses (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE, name VARCHAR (32), category_id INTEGER);

DROP TABLE IF EXISTS students;
CREATE TABLE students (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE, name VARCHAR (32), course_id INTEGER);

DROP TABLE IF EXISTS teachers;
CREATE TABLE teachers (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE, name VARCHAR (32), course_id INTEGER);

DROP TABLE IF EXISTS course_student_association; 
CREATE TABLE course_student_association (id integer PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE, course_id INTEGER, student_id INTEGER);

DROP TABLE IF EXISTS course_teacher_association; 
CREATE TABLE course_teacher_association (id integer PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE, course_id INTEGER, teacher_id INTEGER);

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;